<?php
/**
 * Frenet Shipping Gateway
 *
 * @category Frenet
 *
 * @author Tiago Sampaio <tiago@tiagosampaio.com>
 * @link https://github.com/tiagosampaio
 * @link https://tiagosampaio.com
 *
 * Copyright (c) 2020.
 */

/**
 * @var Frenet_Shipping_Block_Catalog_Product_View_Quote $this
 * @var Mage_Catalog_Model_Product $product
 */

$product = $this->getProduct();
?>

<?php if ($product->isSaleable()) :?>
    <div class="box-frenet-quote">
        <div class="fieldset">
            <h2><?php echo $this->__('Shipping Quote')?></h2>
            <p><?php echo $this->__('Calculate the shipping quote for this product with Frenet.')?></p>
            <div class="field">
                <label class="label" for="frenet-postcode-field">
                    <span><?php echo $this->__('Postcode') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="postcode"
                           id="frenet-postcode-field"
                           min="0"
                           value=""
                           maxlength="9"
                           class="input-text postcode required"
                           data-bind="value: postcode, event: {change: activate}, attr: {title: fieldTitle}"
                    />
                </div>
            </div>
            <div class="actions">
                <button type="button" id="frenet-postcode-button" class="button btn-cart">
                    <span><?php echo $this->__('Get Quote')?></span>
                </button>
            </div>
            <div class="table-wrapper">
                <div data-bind="visible: error">
                    <span class="text-red" data-bind="text: errorMessage"></span>
                </div>
                <div data-bind="visible: displayNoResults">
                    <span data-bind="text: noResultsMessage"></span>
                </div>
                <table id="frenet-result-table" class="data-table" style="display: none;">
                    <col width="60%">
                    <col width="20%">
                    <col width="20%">
                    <thead>
                    <tr>
                        <th><?php echo $this->__('Description') ?></th>
                        <th><?php echo $this->__('Delivery Time') ?></th>
                        <th><?php echo $this->__('Price') ?></th>
                    </tr>
                    </thead>
                    <tbody id="frenet-result-table-body">
                    </tbody>
                </table>
            </div>
            <div id="frenet-loader">
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var config = {
            priceFormat: JSON.parse('<?php echo json_encode(Mage::app()->getLocale()->getJsPriceFormat()) ?>')
        };
        var quote = new ProductQuote(config);
    </script>
<?php endif; ?>
