<?php
/**
 * Frenet Shipping Gateway
 *
 * @category Frenet
 *
 * @author Tiago Sampaio <tiago@tiagosampaio.com>
 * @link https://github.com/tiagosampaio
 * @link https://tiagosampaio.com
 *
 * Copyright (c) 2020.
 */

/**
 * @var Frenet_Shipping_Block_Catalog_Product_View_Quote $this
 * @var Mage_Catalog_Model_Product $product
 */

$product = $this->getProduct();
?>

<?php if ($product->isSaleable()) :?>
<!--    <script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "Magento_Ui/js/core/app": --><?//= $block->getJsLayout() ?>
<!--        }-->
<!--    }-->
<!--    </script>-->
    <div class="box-frenet-quote" data-bind="scope: 'frenet-quote'">
        <div class="fieldset">
            <h2><?php echo $this->__('Shipping Quote')?></h2>
            <p><?php echo $this->__('Calculate the shipping quote for this product with Frenet.')?></p>
            <div class="field">
                <label class="label" for="frenet-postcode-field">
                    <span><?php echo $this->__('Postcode') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="postcode"
                           id="frenet-postcode-field"
                           min="0"
                           value=""
                           maxlength="9"
                           class="input-text postcode"
                           data-validate="required: true"
                           data-bind="value: postcode, event: {change: activate}, attr: {title: fieldTitle}"
                    />
                </div>
            </div>
            <div class="actions">
                <button type="button" id="frenet-postcode-button" class="button btn-cart">
                    <span><?php echo $this->__('Get Quote')?></span>
                </button>
            </div>
            <div class="table-wrapper">
                <div data-bind="visible: error">
                    <span class="text-red" data-bind="text: errorMessage"></span>
                </div>
                <div data-bind="visible: displayNoResults">
                    <span data-bind="text: noResultsMessage"></span>
                </div>
                <table data-bind="visible: visible" class="data table">
                    <col width="60%">
                    <col width="10%">
                    <col width="10%">
                    <thead>
                    <tr>
                        <th data-bind="i18n: 'Description'"></th>
                        <th data-bind="i18n: 'Time'"></th>
                        <th data-bind="i18n: 'Price'"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <!-- ko foreach: rates -->
                    <tr>
                        <td data-bind="text: service_description"></td>
                        <td data-bind="text: delivery_time"></td>
                        <td data-bind="text: shipping_price"></td>
                    </tr>
                    <tr data-bind="visible: message" class="footer">
                        <td colspan="4">
                            <small class="note" data-bind="text: message"></small>
                        </td>
                    </tr>
                    <!-- /ko -->
                    </tbody>
                </table>
            </div>
            <div id="frenet-loader" data-mage-init='{"loader": {}}'>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var productQuote = Class.create();
        productQuote.prototype = {
            initialize: function () {
                this.url = '/frenet/product/quote';
                this.postcode = null;
                this.active = false;
                this.field = $('frenet-postcode-field');
                this.button = $('frenet-postcode-button');

                // this.field.observe('change', this.updateRates.bind(this));
                this.button.observe('click', this.updateRates.bind(this));
            },
            updateRates: function () {
                this.postcode = this.field.value;
                if (this.postcode) {
                    // this.loaderStart();

                    new Ajax.Request(this.url, {
                        method: 'POST',
                        parameters: $('product_addtocart_form').serialize(),
                        onSuccess: this.processSuccess.bind(this),
                        onFailure: this.processFailure.bind(this),
                        onComplete: this.processAlways.bind(this)
                    });
                }

                // if (!this.postcode()) {
                //     this.reset();
                // }
            },
            processSuccess: function (result) {
                console.log("RESULT SUCCESS", result);
                // if (result.error) {
                //     this.processFailure(result);
                //     return;
                // }

                // this.pushRates(result.rates);
            },
            processFailure: function (result) {
                console.log("RESULT FAILURE", result);
                // this.reset();
                // this.errorMessage(result.message);
                // this.error(true);
            },
            processAlways: function (result) {
                console.log("RESULT ALWAYS", result);
                // this.loaderStop();
            },
        }

        var quote = new productQuote();
    </script>
<?php endif; ?>
